# fly.toml app configuration file generated for voxmail on 2025-10-06T20:07:37+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'voxmail'
primary_region = 'ewr'
console_command = '/bin/bash'

[build]

[env]
  PORT = '8080'
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  memory = '2048mb'
  cpu_kind = 'shared'
  cpus = 1
